# Generated by Django 5.1.7 on 2025-04-04 19:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('linkedin_id', models.URLField(blank=True, null=True)),
                ('github_id', models.URLField(blank=True, null=True)),
                ('summary', models.TextField()),
                ('skills', models.TextField()),
                ('certifications', models.TextField(blank=True, null=True)),
                ('languages', models.TextField(blank=True, null=True)),
                ('hobbies', models.TextField(blank=True, null=True)),
                ('education', models.JSONField(default=list)),
                ('experience', models.JSONField(default=list)),
                ('projects', models.JSONField(default=list)),
                ('template_choice', models.CharField(default='1', max_length=1)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
