# Generated by Django 5.1.7 on 2025-04-08 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf', '0002_profile_feedback_profile_last_analyzed_profile_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='ai_suggestions',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
