# Generated by Django 5.1.7 on 2025-04-08 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pdf', '0003_profile_ai_suggestions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='github_id',
        ),
    ]
