# Generated by Django 5.2 on 2025-04-17 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pdf', '0004_remove_profile_github_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='hobbies',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='languages',
        ),
    ]
